CREATE TABLE IF NOT EXISTS ProxyConfiguration (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  port VARCHAR(10) NOT NULL,
  address VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
);

CREATE TABLE IF NOT EXISTS DataSource (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(250) NOT NULL,
  port VARCHAR(10) NOT NULL,
  address VARCHAR(250) NOT NULL,
  table_name VARCHAR(100),
  jdbc_connectionstring VARCHAR(500),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
);

CREATE TABLE IF NOT EXISTS DarwinCoreColumns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datasource_name VARCHAR(50) NOT NULL,
  darwincore_name VARCHAR(250) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
);
