name: Compilar e lançar versão do spLinker

on:
  push:
    branches:
      - master
jobs:
  test:
    name: "Testes automatizados do Maven"
    runs-on: ubuntu-latest
    env:
      CURRENT_DIR: ${{ github.workspace }}
      SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64
          lfs: true
          path: src
      
      - name: Testes automatizados
        run: mvn clean test

  build-on-windows:
    needs: test
    name: "Compilação para Windows"
    runs-on: windows-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64

      - name: Maven - Instalar bibliotecas, compilar, executar testes automatizados e empacotar 
        run: mvn package -DskipTests
        
      - name: Criar image jpackage
        run: jpackage --type app-image --name spLinker --input target/ --main-jar splinker-1.0-SNAPSHOT.jar

      - name: Criar pasta do yajsync
        run: mkdir spLinker\libs
      
      - name: Copiar yajsync
        run: cp libs\yajsync-app-0.9.0-SNAPSHOT-full.jar spLinker\libs;

      - name: Copia arquivo de configuração do Log4J/Sentry
        run:  cp .\src\main\resources\log4j2.xml .\spLinker\

      - name: Empacotar para Windows
        run: jpackage --name spLinker --app-image spLinker --type msi --dest dist\windows --win-shortcut  --win-dir-chooser --win-per-user-install
        # --icon app.ico

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: splinker-windows
          path: dist
          retention-days: 3

  build-on-linux:
      needs: test
      runs-on: ubuntu-latest
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - name: Configurar Java
          uses: actions/setup-java@v3
          with:
            java-version: 21
            distribution: 'temurin'
            architecture: x64

        - name: Maven - Instalar bibliotecas, compilar, executar testes automatizados e empacotar 
          run: mvn package -DskipTests
    
        - name: Criar image jpackage
          run: jpackage --type app-image --name spLinker --input target/ --main-jar splinker-1.0-SNAPSHOT.jar

        - name: Criar pasta do yajsync
          run: mkdir ./spLinker/libs
        
        - name: Copiar yajsync
          run: cp ./libs/yajsync-app-0.9.0-SNAPSHOT-full.jar ./spLinker/libs;

        - name: Copiar arquivo de configuração do Log4J/Sentry
          run:  cp ./src/main/resources/log4j2.xml ./spLinker

        - name: Empacotar para Deb
          run: jpackage --name spLinker --type deb --dest dist --linux-shortcut --app-image spLinker

        - name: Instalar empacotador RPM
          run: sudo apt-get install fakeroot

        - name: Empacotar para RPM
          run: jpackage --name spLinker --type rpm --dest dist/linux --linux-shortcut --app-image spLinker

        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: splinker-linux
            path: dist
