name: Maven Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CURRENT_DIR: ${{ github.workspace }}
      IS_GITHUB_FLOW: true
      SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64
          lfs: true
          path: src
      
      - name: Testes automatizados
        run: mvn clean test
