name: Workflow de Release 

on:
  workflow_run:
    workflows: ["Compilar spLinker para Windows e Linux"]
    branches: ['v*.*.*']
    types:
      - completed
jobs:
  steve:
    name: "Steve Jobs"
    runs-on: ubuntu-latest
    steps:
      - name: "Do something"
        run: "echo 'hello mom!';"