name: Compilar e empacotar o spLinker para Windows

on:
  push:
    branches:
      - master

jobs:
  build-on-windows:
    runs-on: windows-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64

      - name: Maven - Instalar bibliotecas, compilar, executar testes automatizados e empacotar 
        run: mvn package -DskipTests
        
      - name: Criar image jpackage
        run: jpackage --type app-image --name spLinker --input target/ --main-jar splinker-1.0-SNAPSHOT.jar

      - name: Criar pasta do yajsync
        run: mkdir spLinker\libs
      
      - name: Copiar yajsync
        run: cp libs\yajsync-app-0.9.0-SNAPSHOT-full.jar spLinker\libs;

      - name: Criar pasta do arquivo SQL
        run: mkdir spLinker\scripts; mkdir spLinker\scripts\sql;

      - name: Copiar arquivo SQL
        run: cp scripts\sql\create_tables.sql spLinker\scripts\sql 

      - name: Copia arquivo de configuração do Log4J/Sentry
        run:  cp .\src\main\resources\log4j2.xml .\spLinker\

      - name: Empacotar para Windows
        run: jpackage --name spLinker --app-image spLinker --type msi --dest dist --win-shortcut  --win-dir-chooser --win-per-user-install
        # --icon app.ico

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist
          retention-days: 3
